name: Pull Request Build

on:
  push:
    branches-ignore:
      - "master"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Configure Git user
        run: |
          git config user.email "apis@streammachine.io"
          git config user.name "Stream Machine"
      - name: Configure GPG Key
        run: |
          mkdir -p ~/.gnupg/
          printf "$GPG_PRIVATE_KEY" | base64 --decode > ~/.gnupg/private.key
          gpg --import ~/.gnupg/private.key
        env:
          GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
      - name: Publish
        uses: burrunan/gradle-cache-action@v1
        env:
          MAVEN_OSSRH_USER: ${{secrets.MAVEN_OSSRH_USER}}
          MAVEN_OSSRH_PASSWORD: ${{secrets.MAVEN_OSSRH_PASSWORD}}
          GPG_KEYNAME: ${{secrets.GPG_KEYNAME}}
          GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
        with:
          arguments: build --build-cache
          gradle-version: wrapper
