name: Pull Request Build

on:
  push:
    branches-ignore:
      - "master"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Configure Git user
        run: |
          git config user.email "apis@streammachine.io"
          git config user.name "Stream Machine"
      - name: Publish
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build --build-cache
          gradle-version: wrapper
          properties: |
            gpgPrivateKey=${{secrets.GPG_PRIVATE_KEY}}
            gpgPassphrase=${{secrets.GPG_PASSPHRASE}}
            sonatypeUsername=${{secrets.MAVEN_OSSRH_USER}}
            sonatypePassword=${{secrets.MAVEN_OSSRH_PASSWORD}}
