name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
          gradle-version: wrapper
          properties: |
            gpgPrivateKey=${{secrets.GPG_PRIVATE_KEY}}
            gpgPassphrase=${{secrets.GPG_PASSPHRASE}}
            sonatypeUsername=${{secrets.MAVEN_OSSRH_USER}}
            sonatypePassword=${{secrets.MAVEN_OSSRH_PASSWORD}}
