name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Configure Git user
        run: |
          git config user.email "apis@streammachine.io"
          git config user.name "Stream Machine"
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_PRIVATE_KEY" | base64 --decode | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: ./mvnw -S .mvn/settings.xml --batch-mode --update-snapshots verify -Dgpg.skip
      - name: Publish to Maven Central
        run: ./mvnw -S .mvn/settings.xml -B deploy
        env:
          MAVEN_OSSRH_USER: ${{secrets.MAVEN_OSSRH_USER}}
          MAVEN_OSSRH_PASSWORD: ${{secrets.MAVEN_OSSRH_PASSWORD}}
          GPG_KEYNAME: ${{secrets.GPG_KEYNAME}}
          GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}

